
<img src="img/logo_wiwi.png" width="25%" align="left">

<img src="img/decision_analytics_logo.png" width="17%" align="right">



<br><br><br><br><br><br><br><br>



# Algorithmen und Datenstrukturen(A+D)-Projekt 

**Sommersemester 2025**


# 1. Einführung


<br>

<br>
<br>

**J-Prof. Dr. Michael Römer**

Juniorprofessur für Decision Analytics  | Universität Bielefeld

In [7]:
import matplotlib.pyplot as plt
import numpy as np

## 31-M30 Profilmodul Algorithmen und Datenstrukturen 

- Pflichtmodul im Profil "Data Science" für 1-Fach Bachelor Wiwi
- Wahlflichtmodul für die übrigen Profile im 1-Fach Bachelor Wiwi
- Wahlpflichtmodul / Profilmodul für Bachelor-Studierende mit Nebenfach Wiwi


bestehend aus:

- Vorlesung: Problemlösung mit Algorithmen und Datenstrukturen  (Wintersemester), 4LP, Klausur
- Praktische Übung (Wintersemester),  2 LP,  unbenotete Studienleistung
- **A+D-Projekt (Sommersemester), 4 LP, Prüfungsleistung Hausarbeit**


><div class="alert alert-block alert-info">
<b>Haben Sie bereits Vorlesung und Übung besucht?   </b></div>  

><div class="alert alert-block alert-info">
<b>Wenn ja: Im WS 24 / 25 oder davor?</b></div>  

## Was machen wir heute?

- Gegenseitige Vorstellung
- Ziele, Vorgehen und Aufbau des Kurses
- Wiederholung und Vertiefung Greedy-Algortihmen am Beispiel des Rucksack-Problems

## Wer sind die Dozenten? 

### J.-Prof. Dr. Michael Römer
(michael.roemer@uni-bielefeld.de)
#### Persönliches:
- Wirtschaftsinformatik Studium an der Universität Paderborn
- Promotion an der Martin Luther Universität Halle-Wittenberg zu Airline Crew Planning and Scheduling
- 2017-2019 Forschung in Toronto und Montreal
- Seit Dezember 2019: Juniorprofessor für Decision Analytics an der Universität Bielefeld

#### Dieser Kurs:
- Modulverantwortlicher
- Dozent der wöchentlichen Vorlesungen
- Betreuung von Projektgruppen

## Wer sind die Dozenten? 


### J.-Prof. Dr. Michael Römer
#### Forschungsschwerpunkte:
- Mathematische Optimierung
- Graphenbasierte Modellierung von Optimierungsproblemen
- Decision Diagrams
- Simulation
- Machine Learning

#### Anwendungsbereiche:
- Logistik
- Personaleinsatzplanung
- Gesundheitswesen

## Wer sind Sie?

><div class="alert alert-block alert-info">
<b>In welchem Semester sind Sie?   </b></div>  

><div class="alert alert-block alert-info">
<b>Welchen Studiengang belegen Sie? <br>   </b></div>  

><div class="alert alert-block alert-info">
<b>Haben Sie Programmiererfahrung? </b></div>  

## Welche Vorkenntnisse erwarten wir?

**Wir setzen die Inhalte aus *Problemlösen mit Algorithmen und Datenstrukturen (WS 24/25)* voraus!**
- Einfache Datenstrukturen und Algorithmen, insbes.:
  - Breitensuche
  - Kürzeste Wege
  - Greedy-Verfahren
  - Grundlegendes Verständis von Laufzeitkomplexität von Algorithmen
  - Grundlegende Datenstrukturen (insbes. Graphen) und deren Einsatz in Algorithmen
  - Einführung in Dynamische Programmierung
- ...und die (einfache) Implementierung dieser Dinge in Python


**Falls Sie:**
- die AuD-Vorlesung und Übung **noch nicht** besucht haben, empfehlen wir Ihnen:
  - dies zunächst zu tun und diese Projektveranstaltung im nächsten Jahr zu besuchen
- die AuD-Vorlesung und Übung **im WS 20/21 oder früher** besucht haben, empfehlen wir Ihnen:
  - den Stoff nachzuarbeiten, bitte kontaktieren Sie uns in diesem Fall per E-Mail.



## Was ist die Idee dieses Kurses?

Im Kurs **Problemlösen mit Algorithmen und Datenstrukturen** haben wir 
- grundlegende Algorithmen und Datenstrukturen und
- deren Implementierung in Python kennengelernt

Wir haben allerdings lediglich:
-  **sehr kleine Beispiele** betrachtet
-  **grundlegende Varianten von Algorithmen** betrachtet
- **sehr einfache Implementierungen** durchgeführt
- **wenig eigenständig** gearbeitet

**Die Idee dieses Kurses** besteht darin, in Form von **Projektarbeit in Kleingruppen** diese Einschränkungen zu überwinden. In jedem Projekt wird:
- ein grundlegendes (schweres) kombinatorische Optimierungsproblem betrachtet
- für das in Gruppenarbeit ein Algorithmus entwickelt und in Python implementiert wird
- insbesondere sollen dabei (relativ) einfache Prinzipien und Verfahren der KI-/Baumsuche (Tree Search) angewendet werden
  - keine Sorge: diese Prinzipien vermitteln wir Ihnen in den ersten Veranstaltungen!
- Implementierung soll auf nicht-triviale Probleminstanzen angewendet und auf Basis von Experimenten evaluiert werden


## Ziele des Kurses

Im Kurs 
- vertiefen Sie Ihre Kenntnisse aus der Vorlesung und wenden diese auf eine konkrete Fragestellung an
- sammeln Sie vertiefte Erfahrungen mit der praktischen Implementierung 
- üben Sie, im Team zu arbeiten
- lernen Sie, mit Varianten von Algorithmen zu experimentieren, um
  - Algorithmen weiterzuentwickeln
  - eine geeignete Variante auszuwählen
- lernen Sie **grundlegende Prinzipien und Denkweisen der Dynamischen Programmierung und von (Baum-)Suchverfahren (Tree Search)** kennen, die die Grundlage für **fortgeschrittene Methoden**, z.B.  *Metaheuristiken* oder *Reinforcement Learning* bilden




## Lernformate

In **Präsenzveranstaltungen** werden Inhalte vermittelt, die für das Projekt relevant sind: 
- anhand von Beispielen werden algorithmische Prinzipien erläutert, die im Projekt angewendet und verfeinert werden können
- erweiterte Techniken und Pakete in Python, die nützlich sein können
- Einlesen von Probleminstanzen und Experimentieren mit Algorithmen
- ggf. Tools zum gemeinsamen Entwickeln von Code


In **Projektarbeiten** 
- arbeiten Sie in Gruppen von idealerweise **3-4 Personen** gemeinsam an der Entwicklung und Implementierung
- an einem Problem der **kombinatorischen Optimierung**
- jede Gruppe wird **von einem Dozenten** betreut, mit dem regelmäßige Treffen vereinbart werden sollten

In **zwei Präsentationen je Gruppe** werden
- Zwischenergebnisse und Abschlussergebnisse vorgestellt

In einem **gemeinsamen Projektbericht** werden
- die Projektergebnisse aufbereitet und
- wissenschaftliches Schreiben geübt



## Lehrmaterialien

#### "Ausführbare Folien"
- diese Slides sind / basieren auf **Jupyter Notebooks**
- sie enthalten (z.T.) ausführbaren Code
- können in verschiedenen Formaten abgerufenen werden und entweder lokal oder online ausgeführt werden


## Moodle

Im Moodle gibt es
- aktuelle Informationen zum Kurs
- die Jupyter-Notebooks / Links zu Colab-Versionen der Notebooks


## Prüfungsleistung




Formale Prüfungsleistung ist der **Projektbericht**
- wird von der Gruppe gemeinsam erstellt
- als Anlage: kurze Beschreibung der Beiträge der einzelnen Teilnehmer*innen
- Umfang: ca 20-30 Seiten pro Gruppe

Wir behalten uns vor, Einzelgespräche mit Gruppenmitgliedern zu führen, wenn wir den Eindruck haben, dass eine eine Binnendifferenzierung in einer Gruppe angezeigt ist.

## Grober zeitlicher Ablauf des Kurses

- **Bis Ende April / Anfang Mai:** Präsenzlehre zur Vermittlung von Grundlagen
  - **Dienstag, 14:15 bis 15:45 Uhr im Raum W9-109**
  
  
- **Dritte / vierte Semesterwoche:** Bildung der Projektgruppen und Vergabe der Aufgabenstellungen


- **Mitte / Ende Mai:** Zwischenpräsentationen


- **Ende Juni:** Abgabe der Projektberichte 


- **Anfang Juli:** Abschlusspräsentationen


**Ziel:** Die Ergebnisse  dieser Veranstaltung werden bis zum **15. Juli 2025** verbucht, damit sie bei der  Bewerbung für den Data Science-Studiengang eingebracht werden können.

# Wiederholung aus  der Vorlesung: Greedy-Verfahren 

## Was tun, wenn für ein Optimierungsproblem kein effizienter Algorithmus bekannt ist?

- für viele NP-harte Probleme wie das das Shortest Hamiltonian Path-Problem (SHPP) und das Traveling Salesperson-Problem (TSP) sind keine effizienten Algorithmen bekannt
- was kann man tun, wenn man dennoch ein großes TSP, z.B. mit 10000 Städten lösen möchte?

#### Idee: Man gibt die Optimalitätsforderung auf!

Wenn man es nicht schafft, in kurzer Zeit eine exakte / optimale Lösung zu finden,
- kann man versuchen, in kurzer Zeit eine **gute** Lösung zu finden!
- Verfahren, die das für Optimierungsprobleme versuchen, nennt man **Heuristiken**
- ein besonders einfacher und allgemeiner Ansatz nennt sich **Greedy-Verfahren** (greedy = gierig)
 - diesen Ansatz werden wir nun näher betrachten

## Ein Greedy-Ansatz für das Shortest Hamiltonian Path-Problem: Nearest-Neighbor

<img src="./img/greedy/32.png" width="20%" align="right">


Eine einfache und sehr bekannte Heuristik für das SHPP (und das TSP) nennt sich **nearest neighbor**:
- man startet bei einem Knoten und
- wählt in jedem Schritt immer den Knoten aus, der dem aktuellen am nächsten ist:

Beispiel rechts: wir starten in Marin und suchen immer den nächsten Nachbarn

><div class="alert alert-block alert-info">
<b> Welche Laufzeitkomplexität weist dieser Algorithmus auf? </b></div>



## Vereinfachte Definition: Greedy-Algorithmus

#### Kernidee von Greedy-Algorithmen
- der Algorithmus geht Schritt für Schritt vor
- die Auswahl des nächsten Schritts / der nächsten Aktion erfolgt "gierig", d.h.
  - es wird ein (lokales) Kriterium definiert (z.B. Entfernung zu den Nachbarn) und
  - eine "lokal optimale"  Aktion (ein lokal optimaler nächster Schritt) gewählt (z.B. der Nachbar mit der niedrigsten Entfernung)

#### Beachte: 
Die "lokal optimale" Auswahl ist in der Regel nicht "global optimal"

### Greedy für das Rucksack-Problem

## Das Rucksack-Problem (Knapsack Problem)

Ein weiteres bekanntes Problem, das einfach zu verstehen, aber (für große Instanzen) schwer zu lösen ist, ist das

#### Rucksack-Problem (Knapsack Problem)

- Gegeben ist ein Rucksack, der ein **Maximalgewicht** fassen kann,
- sowie Gegenstände, die eingepackt werden können. Diese haben jeweils
  - ein Gewicht und
  - einen Wert
- das Ziel ist es, eine Menge von Gegenständen einzupacken, 
  - die das Maximalgewicht nicht überschreitet und
  - einen möglichst großen Wert hat
  

Wie das TSP ist dieses Optimierungsproblem NP-schwer!

## Das Rucksack-Problem: Beispiel

<img src="./img/greedy/07.png" width="20%" align="right">

Nehmen wir an, du bist ein habgieriger Dieb. Du kannst in deiner Tasche maximal 35 Pfund transportieren und dich interessieren folgende drei Gegenstände:



<img src="./img/greedy/08.png" width="40%" align="left ">

Was passiert, wenn wir als Greedy-Regel immer **den wertvollsten** noch passenden Gegenstand in den Rucksack packen?

### Rucksack-Beispiel: Greedy-Lösung vs Optimale Lösung

Die Lösung mit dem genannten Greedy-Ansatz sieht wie folgt aus:

<img src="./img/greedy/09.png" width="40%" align="middle">

Es ist leicht zu sehen, dass die optimale Lösung anders aussieht:
<img src="./img/greedy/10.png" width="20%" align="middle">

## Greedy-Algorithmus: Implementierung in Python

In [9]:
def greedy_knapsack(values, weights, capacity):
    solution = [] # Array mit Lösungen
    obj_val=0 # akkumulierter Wert
    total_weight=0 # akkumuliertes Gewicht
    
    for i in range(len(values)): 
        if total_weight + weights[i] <= capacity: ## wenn das item noch reinpasst...
            solution.append(i) ## füge es hinzu und
            total_weight+= weights[i] # erhöhe das verbrauchte Gewicht
            obj_val += values[i] # und den Zielfunktionswert
            
    return obj_val, solution


.. probieren wir es aus:

In [11]:
values = [3000,2000,1500]
weights = [30,20,15]
capacity = 35

greedy_knapsack(values, weights, capacity)

(3000, [0])

## Verbesserungsidee Greedy-Algorithmus: Sortieren der Elemente

Welche Sortierungen wären sinnvoll?

Wie kann man eine solche Sortierung implementieren?

## Sortierung: Nutzung von vorhandenen Funktionen

- in "reinem" Python: `sorted(liste)` gibt die Liste 

In [12]:
sorted(weights)

[15, 20, 30]

- in `numpy` gibt es eine Reihe von Sortierfunktionen, z.B. `sort`

In [13]:
np.sort(weights)

array([15, 20, 30])

**Problem:** Wir haben jetzt zwar die sortierten Gewichte, aber wir möchten wissen, zu welchen Items / Gegenstände zu diesen gehören!

## Sortierung: Wie können wir beide Arrays "simultan" sortieren?

- in `numpy` gibt es die Funktion `argsort`, die nicht die sortierten Elemente zurückgibt, sondern die Indizes der Elemente:

In [16]:
sorted_indexes = np.argsort(weights)
sorted_indexes

array([2, 1, 0], dtype=int64)

- diese sortierten Indizes können zum umsortieren von `numpy`-arrays wie folgt genutzt werden:

In [19]:
values = np.array(values)
weights = np.array(weights)

values_sorted_by_weight = values[sorted_indexes]
weights_sorted_by_weight = weights[sorted_indexes]

print(sorted_indexes)
print(values_sorted_by_weight)
print(weights_sorted_by_weight)



[2 1 0]
[1500 2000 3000]
[15 20 30]


## Greedy-Knapack mit aufsteigend nach Gewicht sortiertem Array:

In [20]:
greedy_knapsack(values_sorted_by_weight, weights_sorted_by_weight, capacity)

(3500, [0, 1])

## Sortierung: Wie können wir die Arrays nach einem anderen Kriterium sortieren?

Mögliche Sortierungen wären:
- absteigend nach Wert
- absteigend nach Wert / Gewicht


**Einfacher Ansatz** zum Erhalt einer **absteigenden Sortierung**: Multiplikation mit -1

In [21]:
negative_values = values * -1
sorted_indexes = np.argsort(negative_values)

values_sorted = values[sorted_indexes]
weights_sorted = weights[sorted_indexes]
values_sorted

array([3000, 2000, 1500])

**Einfacher Ansatz** zum Erhalt einer **absteigenden Sortierung nach Wert / Gewicht**: Bildung eines Hilfsarrays

In [24]:
negative_ratio = values/weights * -1

print(negative_ratio)

sorted_indexes = np.argsort(negative_ratio)

values_sorted = values[sorted_indexes]
weights_sorted = weights[sorted_indexes]
values_sorted

[-100. -100. -100.]


array([3000, 2000, 1500])

## Genug Sandkasten-Beispiele: Größere Probleminstanzen

- eines der Ziele dieser Veranstaltung besteht darin, auch größere / schwierigere Probleme zu lösen
  - genauer gesagt: größere / schwierigere **Probleminstanzen**
- wir könnten solche Instanzen (zufällig) generieren
- es existieren jedoch für grundlegende kombinatorische Optimierungsprobleme in der Regel eine Reihe von bekannten Probleminstanzen, die z.B. in Form von strukturierten Textdateien vorliegen
- diese können z.B. zum Vergleich / Benchmarking von Algorithmen verwendet werden
- es gibt auch für viele schwere Probleme so genannte "offene" Instanzen, die bisher noch nicht optimal gelöst wurden

  


## Probleminstanzen für das Rucksackproblem

- für das Rucksackproblem gibt es sehr viele Instanzen
- ein bekannter Satz von Instanzen wurde von D. Pisinger erstellt
- wir haben ein paar dieser Instanzen im Instanz-Ordner zu diesem Foliensatz hinterlegt

Für einige dieser Instanzen findet man unter folgendem Link die optimalen Lösungen:

http://artemisa.unicauca.edu.co/~johnyortega/instances_01_KP/


## Dateiformat der Rucksack-Probleminstanzen

Die Instanzdateien haben folgendes Format:

- erste Zeile: `anzahl_items` `kapazität`
- jede weitere Zeile enthält für jedes Item: `wert` `gewicht`

Unser "Sandkastenbeispiel" sähe in diesem Format wie folgt aus:

## Einlesen von Probleminstanzen

Wollen wir die bekannten Instanzen nutzen, so müssen wir: 
- die Daten aus den Textdateien auslesen und
- in Datenstrukturen überführen, die wir für unsere Algorithmen nutzen können:

In [26]:
def read_knapsack_instance(instance_path, filename):
    weights=[]
    values=[]
    with open(instance_path + filename) as f: # öffne die Datei
        line = f.readline().split()  # splitte die erste Zeile in Einzelelemente
        number_of_items = int(line[0]) # lese die Anzahl items aus Zeile 1 aus
        capacity = int(line[1]) # lese die Kapazität aus
        for i in range(number_of_items): # lese die Werte der einzelnen Items aus
            line = f.readline().split() # lese Zeile aus Datei und splitte die Zeile in Einzelelemente
            values.append(int(line[0])) # lese den Wert
            weights.append(int(line[1])) # lese das Gewicht
    return np.array(values), np.array(weights), capacity

... probieren wir es aus an einer Instanz mit 5000 Items:

In [31]:
instance_path = "../instances/knapsack/"

filename = "knapPI_1_5000_1000_1"

values, weights, capacity  = read_knapsack_instance(instance_path, filename)
capacity

25016

## Einlesen von Probleminstanzen in Colab:
- einmal folgende Zelle ausführen zum Herunterladen:

In [ ]:
!npx degit decision-analytics/AuDProjekt2024/instances -f

- dann brauchen wir zum Einlesen einen etwas anderen Pfad:

In [ ]:
instance_path = "./knapsack/"
filename = "knapPI_1_5000_1000_1"

values, weights, capacity  = read_knapsack_instance(instance_path, filename)

## Lösen der Probleminstanzen

- nun können wir unseren Greedy-Ansatz und veschiedene Sortierungen evaluieren!

In [32]:
values, weights, capacity  = read_knapsack_instance(instance_path, filename)

obj_val, solution = greedy_knapsack(values,weights,capacity)

print ("Zielfunktionswert in der Basisversion:", obj_val)

Zielfunktionswert in der Basisversion: 33727


.. wie gut ist die Lösung im Vergleich zum Optimum? Schauen wir nach:
http://artemisa.unicauca.edu.co/~johnyortega/instances_01_KP/

><div class="alert alert-block alert-info">
<b> Testen Sie den Greedy-Algorithmus mit verschiedenen Sortierungen und vergleichen Sie mit der optimalen Lösung!</b></div>


## Zwischenfazit für das Rucksackproblem
- wie für viele bekannte Optimierungsprobleme gibt es auch für das Rucksackproblem viele Instanzen, die zum Testen / für das Benchmarking genutzt werden können
- Greedy in Kombination mit einer guten Sortierung führt für das Rucksack-Problem oft zu sehr guten Lösungen in kurzer Zeit
- die optimale Lösung wird jedoch in der Regel nicht erreicht!






## Fazit  und Ausblick

#### Heute haben wir:
- zunächst einige wichtige organisatorische Fragen geklärt
- die Idee von Greedy-Verfahren wiederholt
- haben wir anhand des Rucksack-Beispiels wichtige "Projektschritte" durchgespielt:
  - das Einlesen von Probleminstanzen
  - das Experimentieren mit und den Vergleich von verschiedenen algorithmischen Varianten (hier: Greedy mit verschiedenen Sortierungen)
  
#### Beim nächsten Mal (nächste Woche):
- beschäftigen wir uns mit ersten Schritten von Greedy zur Dynamischen Programmierung
- betrachten wir ein weiteres bekanntes Problem - das Traveling Salesman Problem (TSP)

...und in (spätestens) 3  Wochen stellen wir die Gruppen zusammen!
  




